/** The canonical "do not edit" header for generated markdown files. */
export function markdownHeader(source: string): string {
  return [
    "<!--",
    "Generated by AgentFlow.",
    `Source: ${source}`,
    "Do not edit this file directly.",
    "Run: agentflow build",
    "-->",
  ].join("\n");
}

/** Standard provenance keys injected into generated JSON files. */
export function jsonProvenance(source: string): Record<string, unknown> {
  return {
    $generatedBy: "agentflow",
    $source: [source],
    $doNotEdit: true,
  };
}
