import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { compileProject } from "../src/compiler/compileProject.js";

const here = dirname(fileURLToPath(import.meta.url));
const fixture = join(here, "fixtures", "basic");
const inputDir = join(fixture, "input");
const expectedDir = join(fixture, "expected");
const FIXED_TIME = "2026-06-22T00:00:00.000Z";

describe("golden: basic fixture", () => {
  const result = compileProject({ rootDir: inputDir, buildTime: FIXED_TIME });

  it("compiles successfully", () => {
    expect(result.ok).toBe(true);
    expect(result.files.length).toBe(8);
  });

  for (const path of [
    "AGENTS.md",
    "CLAUDE.md",
    "GEMINI.md",
    ".agent/dist/manifest.json",
    ".agent/dist/policy.json",
    ".agent/dist/schemas/manifest.schema.json",
    ".agent/dist/schemas/policy.schema.json",
    ".agent/dist/build-info.json",
  ]) {
    it(`matches golden ${path}`, () => {
      const generated = result.files.find((f) => f.path.split("\\").join("/") === path);
      expect(generated, `missing generated file ${path}`).toBeDefined();
      const expected = readFileSync(join(expectedDir, path), "utf8");
      expect(generated?.content).toBe(expected);
    });
  }

  it("is deterministic across runs", () => {
    const a = compileProject({ rootDir: inputDir, buildTime: FIXED_TIME });
    const b = compileProject({ rootDir: inputDir, buildTime: FIXED_TIME });
    expect(a.files).toEqual(b.files);
  });

  it("only build-info.json varies when the build time changes", () => {
    const a = compileProject({
      rootDir: inputDir,
      buildTime: "2020-01-01T00:00:00.000Z",
    });
    const b = compileProject({
      rootDir: inputDir,
      buildTime: "2030-01-01T00:00:00.000Z",
    });
    for (const fa of a.files) {
      const fb = b.files.find((f) => f.path === fa.path);
      if (fa.path.includes("build-info")) {
        expect(fa.content).not.toBe(fb?.content);
      } else {
        expect(fa.content).toBe(fb?.content);
      }
    }
  });

  it("every markdown file carries the do-not-edit header", () => {
    for (const md of ["AGENTS.md", "CLAUDE.md", "GEMINI.md"]) {
      const f = result.files.find((x) => x.path === md);
      expect(f?.content.startsWith("<!--\nGenerated by AgentFlow.")).toBe(true);
    }
  });
});
